# Generated by Django 5.0.7 on 2024-08-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=1000)),
                ('translated_text', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
    ]
