# Generated by Django 5.0.7 on 2024-08-06 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendCodingChallenge', '0002_alter_translation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
