# Generated by Django 5.0.7 on 2024-08-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendCodingChallenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='type',
            field=models.CharField(choices=[('HTML', 'HTML'), ('PLAIN_TEXT', 'PLAIN_TEXT')], default='PLAIN_TEXT', max_length=10),
        ),
    ]
